// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from 'prisma/config';
import { loadPrismaEnvironmentVariables } from './prisma/env';

// Load environment variables before exporting the Prisma configuration to ensure that all necessary variables are available when Prisma runs,
// especially during migrations and seeding.
loadPrismaEnvironmentVariables();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
