export enum SystemAuditAction {
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
}

export enum AuthAuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS',
  TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_VERIFICATION_FAILURE = 'EMAIL_VERIFICATION_FAILURE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE',
}

export enum UserAuditAction {
  USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS',
  USER_CREATE_FAILURE = 'USER_CREATE_FAILURE',
  USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE',
}

export enum AccountPreferencesAuditAction {
  ACCOUNT_PROFILE_UPDATE_SUCCESS = 'ACCOUNT_PROFILE_UPDATE_SUCCESS',
  ACCOUNT_SETTINGS_UPDATE_SUCCESS = 'ACCOUNT_SETTINGS_UPDATE_SUCCESS',
}

export enum TaskAuditAction {
  TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS',
  TASK_CREATE_FAILURE = 'TASK_CREATE_FAILURE',
  TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS',
  TASK_UPDATE_FAILURE = 'TASK_UPDATE_FAILURE',
  TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILURE = 'TASK_DELETE_FAILURE',
  TASK_ASSIGN_SUCCESS = 'TASK_ASSIGN_SUCCESS',
  TASK_ASSIGN_FAILURE = 'TASK_ASSIGN_FAILURE',
}

export enum ProjectAuditAction {
  PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS',
  PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS',
  PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS',
  PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE',
  PROJECT_OWNER_UPDATE_SUCCESS = 'PROJECT_OWNER_UPDATE_SUCCESS',
  PROJECT_OWNER_UPDATE_FAILURE = 'PROJECT_OWNER_UPDATE_FAILURE',
}

export type AuditAction =
  | SystemAuditAction
  | AuthAuditAction
  | UserAuditAction
  | AccountPreferencesAuditAction
  | TaskAuditAction
  | ProjectAuditAction;
